// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmx1VTPyUBpcqLW4pPO7g71-CSdkrgIdI',
    appId: '1:546378916569:web:751fb7e25507c005d414c8',
    messagingSenderId: '546378916569',
    projectId: 'my-tik-taki',
    authDomain: 'my-tik-taki.firebaseapp.com',
    storageBucket: 'my-tik-taki.firebasestorage.app',
    measurementId: 'G-PWZJK0BE2V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKZFVuvYycmwxBgxMNJWDvUVl9db52g3I',
    appId: '1:546378916569:android:5d0f429dafbe74bfd414c8',
    messagingSenderId: '546378916569',
    projectId: 'my-tik-taki',
    storageBucket: 'my-tik-taki.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxR1Me7QVw4Q1q59BCJ6BytR7c4bnJUXg',
    appId: '1:546378916569:ios:a8e5f50a7f4b7c24d414c8',
    messagingSenderId: '546378916569',
    projectId: 'my-tik-taki',
    storageBucket: 'my-tik-taki.firebasestorage.app',
    iosBundleId: 'com.example.myTikTaki',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxR1Me7QVw4Q1q59BCJ6BytR7c4bnJUXg',
    appId: '1:546378916569:ios:a8e5f50a7f4b7c24d414c8',
    messagingSenderId: '546378916569',
    projectId: 'my-tik-taki',
    storageBucket: 'my-tik-taki.firebasestorage.app',
    iosBundleId: 'com.example.myTikTaki',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDmx1VTPyUBpcqLW4pPO7g71-CSdkrgIdI',
    appId: '1:546378916569:web:5f5570d22b777eead414c8',
    messagingSenderId: '546378916569',
    projectId: 'my-tik-taki',
    authDomain: 'my-tik-taki.firebaseapp.com',
    storageBucket: 'my-tik-taki.firebasestorage.app',
    measurementId: 'G-ZE5RBQE1PP',
  );
}
